---
# tasks file for ansible-role-biomedit-transfers-tool

# Custom setup by distro
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Create the virtualenv and upgraded pip and setuptools
  ansible.builtin.pip:
    name:
      - pip>20.0.2
      - urllib3<2.0
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
    virtualenv_command: "{{ _venv_command }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Uninstall biomedit-transfers (migrated to sett)
  ansible.builtin.pip:
    name: biomedit-transfers
    state: absent
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Install sett[legacy] if this is a Centos7 host
  ansible.builtin.pip:
    name: "sett[legacy]"
    state: latest
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when: _install_sett_legacy
  tags: skip_ansible_lint

- name: Install sett
  ansible.builtin.pip:
    name: "sett"
    state: latest
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  tags: skip_ansible_lint

- name: Install libbiomedit
  ansible.builtin.pip:
    name: "libbiomedit"
    state: latest
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Symlink SET binaries to /usr/local/bin/
  ansible.builtin.file:
    src: "{{ biomedit_transfers_tool_venv_path }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    state: link
  loop:
    - sett
    - sett-gui
  when: biomedit_transfers_tool_add_to_path

- name: Deploy a SETT config to disable version checks to pypi
  block:

    - name: Create folder /etc/sett
      ansible.builtin.file:
        path: /etc/sett
        owner: root
        group: root
        state: directory
        mode: '0755'

    - name: Deploy /etc/sett/config.json to disable version checks to pypi
      ansible.builtin.template:
        dest: /etc/sett/config.json
        src: sett_config.json.j2
        owner: root
        group: root
        mode: 0644

  when: biomedit_transfers_tool_disable_version_check
