---
# tasks file for ansible-role-biomedit-transfers-tool

# Custom setup by distro
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Create the virtualenv and upgraded pip and setuptools
  pip:
    name:
      - setuptools==46.1.3
      - pip==20.0.2
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
    virtualenv_command: "{{ _venv_command }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Uninstall biomedit-transfers (migrated to sett)
  pip:
    name: biomedit-transfers
    state: absent
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Install sett[legacy] if this is a Centos7 host
  pip:
    name: "sett[legacy]=={{ biomedit_transfers_tool_version }}"
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when: _install_sett_legacy

- name: Install sett (latest)
  pip:
    name: "sett=={{ biomedit_transfers_tool_version }}"
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Add the venv binaries to PATH
  blockinfile:
    dest: /etc/profile.d/biomed_transfer_tool_path.sh
    create: yes
    owner: root
    group: root
    mode: 0644
    marker: "# {mark} CREATED WITH ANSIBLE. ADD SETT BINARIES TO PATH"
    content: |
      export PATH={{ biomedit_transfers_tool_venv_path }}/bin:$PATH
  when: biomedit_transfers_tool_add_to_path

- name: Deploy a SETT config to disable version checks to pypi
  block:

    - name: Create folder /etc/sett
      file:
        path: /etc/sett
        owner: root
        group: root
        state: directory
        mode: '0755'

    - name: Deploy /etc/sett/config.json to disable version checks to pypi
      template:
        dest: /etc/sett/config.json
        src: sett_config.json.j2
        owner: root
        group: root
        mode: 0644

  when: biomedit_transfers_tool_disable_version_check
