---

- name: RedHat | Enable EPEL
  yum:
    name: epel-release
    state: installed
  when: biomedit_transfers_tool_install_epel

- name: RedHat | Install python2-setuptools required by the ansible pip module
  yum:
    name: python-setuptools
    state: installed

- name: RedHat | Enable centos-release-scl repository
  yum:
    name: centos-release-scl
    state: installed
  when: biomedit_transfers_tool_install_epel

- name: RedHat | Install python3.8
  yum:
    name:
      - rh-python38
      - rh-python38-python-pip
    state: installed

- name: RedHat | Install dependencies for the GUI
  yum:
    name:
      - libxkbcommon-x11
      - xcb-util-wm
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
    state: installed

- name: RedHat | Define virtualenv binary to use
  set_fact:
    _venv_command: "/opt/rh/rh-python38/root/usr/bin/python3.8 -m venv"

- name: Initialize the venv with the required deps for Centos7
  pip:
    name:
      - setuptools==46.1.3
      - pip==20.0.2
      - PySide2==5.15.2
      - shiboken2==5.15.2
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
    virtualenv_command: "{{ _venv_command }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
